
#tomcat端口号
server:
  port: 80

#mysql
spring:
  datasource:
    #mysql配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_shiro?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    #引入Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#thymeleaf:
#          prefix: classpath:/templates/
#          mode: HTML
#          cache: false
#          encoding: UTF-8
#          #     新版本不支持content-type: text/html，故新写法
#          servlet:
#            content-type: text/html
mybatis:
           mapper-locations: classpath:mapper/*.xml
           type-aliases-package: xyz.herther.pojo
